{% if name_suffix is not defined %}
{% set name_suffix = "3.7" %}
{% endif %}
{% set name = "pypy" ~ name_suffix %}
{% set version = "7.3.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://downloads.python.org/pypy/{{ name }}-v{{ version }}-src.tar.bz2
    sha256: 2ed02ac9e710859c41bc82deafb08619792bb9a27eeaa1676c741ededd214dd7  # [name_suffix == "3.7"]
    sha256: 21ae339f4f5016d6ca7300305f3e3b554373835cb3c39a9041fe30e6811c80c6  # [name_suffix == "3.8"]
    folder: pypy3
    patches:
      - patches/fficurses.patch
      - patches/tklib_build.patch
      - patches/tk_app.patch      # [win]
      - patches/lzma_build.patch  # [win]
      - patches/clibffi.patch     # [osx]
      - patches/darwin.patch      # [osx]
      - patches/site-and-sysconfig-conda.patch    # [win and name_suffix == "3.7"]
      - patches/distutils-install.patch           # [win and name_suffix == "3.7"]
      - patches/distutils-sysconfig-get_python_lib.patch  # [win and name_suffix == "3.7"]
      - patches/0001-Add-conda-forge-version.patch
      - patches/0018-Disable-copying-dlls.patch  # [name_suffix == "3.7"]
      - patches/0019-Disable-copying-dlls.patch  # [name_suffix == "3.8"]
      - patches/0021-Adapt-platform-to-patch-0001.patch
      - patches/0022-Fix-LIBDIR.patch  # [name_suffix == "3.7"]
      - patches/0023-Fix-LIBDIR.patch  # [name_suffix == "3.8"]
      # Patches by @mingwandroid from python-feedstock
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0024-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch  # [name_suffix == "3.8"]
      # Patches to be removed for PyPy7.3.8
      - patches/pre-7.3.7-001-Use-libffi-8.patch
      - patches/pre-7.3.7-002-stdlib.patch           # [name_suffix == "3.7"]
      # WIP Patches for OpenSSL 3.0.0 support
      - patches/vopenssl3-0001-sync-with-rsa.py-cryptography-source.patch     # [openssl == "3"]
      - patches/vopenssl3-0002-sync-with-crypto.py-cryptography-source.patch  # [openssl == "3"]
      - patches/vopenssl3-0003-sync-with-err.py-cryptography-source.patch     # [openssl == "3"]

  - url: https://downloads.python.org/pypy/pypy2.7-v7.3.6-win64.zip           # [win]
    sha256: fcc8f6b3b472a77eaa754951f288fe234b4953bfba845888dd839b9b862cb891  # [win]
    folder: pypy2-binary                                                      # [win]

build:
  number: 1
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3   # [not win]
    - pkg-config        # [unix]
    - pycparser
  host:
    - bzip2
    - expat
    - gdbm     # [not win]
    - jom ==1.1.2  # [win]
    - libffi
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xorg-libx11  # [linux]
    - xz
    - zlib
  run:
    - bzip2
    - expat
    - gdbm     # [not win]
    - libffi
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xz
    - zlib
  run_constrained:
    - pypy3.5 ==99999999999
    - pypy3.6 ==99999999999
    - pypy3.7 ==99999999999  # [name_suffix=="3.8"]
    - pypy3.8 ==99999999999  # [name_suffix=="3.7"]
    - python {{ name_suffix }}.* *_{{ "".join(version.split(".")[:2]) }}_pypy

test:
  commands:
    - pypy3 --help
    - pypy3 -c "import platform; print(platform._sys_version())"
    - test -f $PREFIX/lib-python/3/lib2to3/Grammar{{ name_suffix }}*.pickle                      # [unix and name_suffix=="3.7"]
    - test -f $PREFIX/lib-python/3/lib2to3/PatternGrammar{{ name_suffix }}*.pickle               # [unix and name_suffix=="3.7"]
    - test -f $PREFIX/lib/pypy3.8/lib2to3/Grammar{{ name_suffix }}*.pickle                       # [unix and name_suffix=="3.8"]
    - test -f $PREFIX/lib/pypy3.8/lib2to3/PatternGrammar{{ name_suffix }}*.pickle                # [unix and name_suffix=="3.8"]
    - if not exist %PREFIX%\lib-python\3\lib2to3\Grammar{{ name_suffix }}*.pickle exit 1         # [win]
    - if not exist %PREFIX%\lib-python\3\lib2to3\PatternGrammar{{ name_suffix }}*.pickle exit 1  # [win]

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: >
        PyPy is a Python interpreter and just-in-time compiler. See
        https://conda-forge.org/blog/posts/2020-03-10-pypy for more information
        about using PyPy in conda

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
    - isuruf
    - ocefpaf
    - mattip
