{% if name_suffix is not defined %}
{% set name_suffix = "3.6" %}
{% endif %}
{% set name = "pypy" ~ name_suffix %}
{% set version = "7.3.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://downloads.python.org/pypy/{{ name }}-v{{ version }}-src.tar.bz2
    sha256: a23d21ca0de0f613732af4b4abb0b0db1cc56134b5bf0e33614eca87ab8805af  # [name_suffix == "3.6"]
    sha256: d920fe409a9ecad9d074aa8568ca5f3ed3581be66f66e5d8988b7ec66e6d99a2  # [name_suffix == "3.7"]
    folder: pypy3
    patches:
      - patches/fficurses.patch
      - patches/tklib_build.patch
      - patches/tk_app.patch      # [win]
      - patches/lzma_build.patch  # [win]
      - patches/clibffi.patch     # [osx]
      - patches/darwin.patch      # [osx]
      - patches/site-and-sysconfig-conda.patch    # [win]
      - patches/distutils-install.patch           # [win]
      - patches/distutils-sysconfig-get_python_lib.patch  # [win]
      - patches/0001-Add-conda-forge-version.patch
      - patches/0018-Disable-copying-dlls.patch
      - patches/0021-Adapt-platform-to-patch-0001.patch
      - patches/0022-Fix-LIBDIR.patch
      # Patches by @mingwandroid from python-feedstock
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
      # Patches to be removed for pypy v7.3.6
      - patches/pre-7.3.6-0001.patch
      - patches/pre-7.3.6-0002.patch
      - patches/pre-7.3.6-0003.patch
      - patches/pre-7.3.6-0004.patch
      - patches/pre-7.3.6-0005.patch
      - patches/pre-7.3.6-0006.patch
      - patches/pre-7.3.6-0007.patch
      - patches/pre-7.3.6-0008.patch
      - patches/pre-7.3.6-0009.patch  # [win]
      - patches/pre-7.3.6-0010.patch

  - url: https://downloads.python.org/pypy/pypy2.7-v7.3.5-win64.zip           # [win]
    sha256: 0b90eded11ba89a526c4288f17fff7e75000914ac071bd6d67912748ae89d761  # [win]
    folder: pypy2-binary                                                      # [win]

build:
  number: 10
  skip: True  # [name_suffix=="3.6"]
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3   # [not win]
    - pkg-config        # [unix]
    - pycparser
  host:
    - bzip2
    - expat
    - gdbm     # [not win]
    - jom ==1.1.2  # [win]
    - libffi
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xorg-libx11  # [linux]
    - xz
    - zlib
  run:
    - bzip2
    - expat
    - gdbm     # [not win]
    - libffi
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xz
    - zlib
  run_constrained:
    - pypy3.5 ==99999999999
    - pypy3.6 ==99999999999  # [name_suffix=="3.7"]
    - pypy3.7 ==99999999999  # [name_suffix=="3.6"]
    - python {{ name_suffix }}.* *_{{ "".join(version.split(".")[:2]) }}_pypy

test:
  commands:
    - pypy3 --help
    - pypy3 -c "import platform; print(platform._sys_version())"
    - test -f $PREFIX/lib-python/3/lib2to3/Grammar{{ name_suffix }}*.pickle                      # [unix]
    - test -f $PREFIX/lib-python/3/lib2to3/PatternGrammar{{ name_suffix }}*.pickle               # [unix]
    - if not exist %PREFIX%\lib-python\3\lib2to3\Grammar{{ name_suffix }}*.pickle exit 1         # [win]
    - if not exist %PREFIX%\lib-python\3\lib2to3\PatternGrammar{{ name_suffix }}*.pickle exit 1  # [win]

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: >
        PyPy is a Python interpreter and just-in-time compiler. See
        https://conda-forge.org/blog/posts/2020-03-10-pypy for more information
        about using PyPy in conda

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
    - isuruf
    - ocefpaf
    - mattip
