{% if name_suffix is not defined %}
{% set name_suffix = "3.10" %}
{% endif %}
{% set name = "pypy" ~ name_suffix %}
{% set version = "7.3.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: pypy3
    url: https://downloads.python.org/pypy/{{ name }}-v{{ version }}-src.tar.bz2
    sha256: 5b75af3f8e76041e79c1ef5ce22ce63f8bd131733e9302081897d8f650e81843  # [name_suffix == "3.9"]
    sha256: 4a3a3177d0a1f51d59982bb981d1d485403bda3419d5437b9e077f55f59424ff  # [name_suffix == "3.10"]
    patches:
      - patches/fficurses.patch
      - patches/tklib_build.patch
      - patches/tk_app.patch
      - patches/lzma_build.patch  # [win]
      - patches/clibffi.patch     # [osx]
      - patches/0001-Add-conda-forge-version.patch
      - patches/0021-Adapt-platform-to-patch-0001.patch
      - patches/0023b-Fix-LIBDIR.patch
      - patches/0030-Swap-libffi8-for-7.patch
      # Patches from python-feedstock
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0024-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      - patches/0032-Copy-dependent-libs-for-venvs.patch
      - patches/0001-Fix-TZPATH-on-windows.patch  # [name_suffix == "3.9"]
      - patches/0001-Fix-TZPATH-on-windows-py3.10.patch  # [name_suffix == "3.10"]
      # Patches since the release
      - patches/0010-make-compilation-work-on-old-glibc-2.17-for-conda-fo.patch
      - patches/0011-don-t-crash-on-constfolding-field-reads-from-null-po.patch
      - patches/0012-include-pyexpatns.h-when-building-pyexpat.patch


  - url: https://downloads.python.org/pypy/pypy2.7-v7.3.6-win64.zip           # [win]
    sha256: fcc8f6b3b472a77eaa754951f288fe234b4953bfba845888dd839b9b862cb891  # [win]
    folder: pypy2-binary                                                      # [win]

build:
  number: 0
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python >=2.7,<3   # [not win]
    - pkg-config        # [unix]
    - pycparser
    - expat
  host:
    - bzip2
    - gdbm     # [not win]
    - jom ==1.1.2  # [win]
    - libffi
    - make     # [linux]
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xorg-libx11  # [linux]
    - xz
    - zlib
    - tzdata
  run:
    - bzip2
    - gdbm     # [not win]
    - libffi
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xz
    - zlib
    - tzdata
  run_constrained:
    - pypy3.5 ==99999999999
    - pypy3.6 ==99999999999
    - pypy3.7 ==99999999999
    - pypy3.8 ==99999999999
    - pypy3.9 ==99999999999  # [name_suffix=="3.10"]
    - pypy3.10 ==99999999999  # [name_suffix=="3.9"]
    - python {{ name_suffix }}.* *_73_pypy

test:
  commands:
    - pypy3 --help
    - pypy3 -c "import platform; print(platform._sys_version())"
    - pypy3 -c "import tkinter; tkinter.Tk()"                                                    # [not unix]
    - test -f $PREFIX/lib/pypy{{ name_suffix }}/lib2to3/Grammar{{ name_suffix }}*.pickle         # [unix]
    - test -f $PREFIX/lib/pypy{{ name_suffix }}/lib2to3/PatternGrammar{{ name_suffix }}*.pickle  # [unix]
    - if not exist %PREFIX%\lib\lib2to3\Grammar{{ name_suffix }}*.pickle exit 1                  # [win]
    - if not exist %PREFIX%\lib\lib2to3\PatternGrammar{{ name_suffix }}*.pickle exit 1           # [win]
    # Check that zoneinfo works from Python 3.9 onwards, see upstream issue:
    # https://foss.heptapod.net/pypy/pypy/-/issues/3653 and conda-specific patch
    # patches/0001-Fix-TZPATH-on-windows.patch
    - pypy3 -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - pypy3 -m test.test_ssl
    # make sure Scripts dir exists so downstream entry_points are created successfully
    - if not exist %PREFIX%\Scripts\ exit 1  # [win]

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: >
        PyPy is a Python interpreter and just-in-time compiler. See
        https://conda-forge.org/blog/posts/2020-03-10-pypy for more information
        about using PyPy in conda

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
    - isuruf
    - ocefpaf
    - mattip
