{% set name = "pypy3.6" %}
{% set version = "7.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://downloads.python.org/pypy/{{ name }}-v{{ version }}-src.tar.bz2
    sha256: a23d21ca0de0f613732af4b4abb0b0db1cc56134b5bf0e33614eca87ab8805af
    folder: pypy3
    patches:
      - patches/fficurses.patch
      - patches/tklib_build.patch
      - patches/clibffi.patch  # [osx]
      - patches/darwin.patch  # [osx]
      - patches/distutils.patch
      # Patches by @mingwandroid from python-feedstock
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0020-ppc-jit-fix
      - patches/0021-ppc-test-fix1
      - patches/0022-ppc-test-fix2
      - patches/0023-buffer-format


build:
  number: 0
  skip: true  # [win]
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3
    - pkg-config
    - pycparser
  host:
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - expat
    - ncurses
    - gdbm
    - xz
    - tk
    - bzip2
    - xorg-libx11  # [linux]
  run:
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - ncurses
    - gdbm
    - xz
    - expat
    - bzip2
  run_constrained:
    - pypy3.5 ==99999999999

test:
  commands:
    - pypy3 --help

about:
  home: http://pypy.org/
  license: MIT
  license_family: MIT
  license_file: pypy3/LICENSE
  summary: PyPy is a Python interpreter and just-in-time compiler.

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
    - isuruf
    - ocefpaf
    - mattip
